# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "946c7f95fc6780b88559e90d45ad7f96"
name = "Blogger React - Local"
application_url = "https://layout-implied-charlie-mon.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[events]
api_version = "unstable"
subscription = [ ]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  topics = [
  "orders/create",
  "app_subscriptions/update",
  "app/uninstalled"
]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_locales,read_orders,read_products,read_script_tags,read_themes,read_translations,write_content,write_files,write_products,write_script_tags,write_themes,write_translations"

[auth]
redirect_urls = [ "https://layout-implied-charlie-mon.trycloudflare.com/api/auth/callback" ]

[app_proxy]
url = "https://layout-implied-charlie-mon.trycloudflare.com/api/proxy"
subpath = "blog-analytics"
prefix = "apps"

[pos]
embedded = false
